name = "severless-api-dev"
account_id = "8be772befd147a8df540aae0fa15c047"
compatibility_date = "2022-11-30"
workers_dev = false
main = "./src/index.ts"
minify = true
kv_namespaces = [
    { binding = "KV", preview_id = "a3030e4701ed406ba337ca8bd9108dda", id = "902aa7ef8f574c66a87d80fd9a3e9ebe"}
]

analytics_engine_datasets = [
    {binding = "AE", dataset = "api-dev"}
]
tail_consumers = [
    {service = "worker-ae-analytics-dev", environment = "production"}
]

r2_buckets  = [
  { binding = "PUBLIC_FILES", bucket_name = "public-files-dev", preview_bucket_name = "public-files-dev"}
]

[define]
PRODUCTION = '"false"'

[env.production]
name = "severless-api"
logpush = true
workers_dev = false
kv_namespaces = [
    { binding = "KV", id = "902aa7ef8f574c66a87d80fd9a3e9ebe", preview_id = "a3030e4701ed406ba337ca8bd9108dda" }
]
analytics_engine_datasets = [
    {binding = "AE", dataset = "api-prod"}
]

tail_consumers = [
  { service = "worker-ae-analytics", environment = "production" }
]

r2_buckets  = [
  { binding = "PUBLIC_FILES", bucket_name = "public-files", preview_bucket_name = "public-files-dev"}
]

[triggers]
crons = ["0 * * * *"]


[env.production.define]
PRODUCTION = '"true"'