name = "severless-api-dev"
type = "javascript"
zone_id = ""
account_id = ""
routes = ["serverless.cyberjake.xyz/*"]
workers_dev = true
compatibility_date = "2022-03-02"

kv_namespaces = [
    { binding = "KV", preview_id = "a3030e4701ed406ba337ca8bd9108dda", id = "902aa7ef8f574c66a87d80fd9a3e9ebe" }
]

[build]
command = "npm install && npm run build"
[build.upload]
format = "service-worker"

[vars]
PRODUCTION = "false"

[env.production]
name = "severless-api"
[env.production.vars]
PRODUCTION = "true"
