name = "severless-api-dev"
workers_dev = true
compatibility_date = "2022-06-24"
account_id = "8be772befd147a8df540aae0fa15c047"

kv_namespaces = [
    { binding = "KV", preview_id = "a3030e4701ed406ba337ca8bd9108dda", id = "902aa7ef8f574c66a87d80fd9a3e9ebe"}
]

[build]
command = "npm install && npm run build"

[vars]
PRODUCTION = "false"

[env.production]
name = "severless-api"
kv_namespaces = [
    { binding = "KV", id = "902aa7ef8f574c66a87d80fd9a3e9ebe" }
]
routes = ["serverless.cyberjake.xyz/*"]
[env.production.vars]
PRODUCTION = "true"
